### ISSUE TITLE
Better Elasticsearch Logging

### ISSUE THREAD

**Issue by Bargs** [spenceralger/grunt-esvm#3]
I'd be willing to work on a pull for this, but I wanted to gather some opinions first. I had to work with a vanilla installation of Elasticsearch recently, and I found it tremendously useful to have the INFO logs by default. So at the very least, I would like to change [this line](https://github.com/kreeware/grunt-esvm/blob/master/lib/logClusterLogs.js#L14) from `grunt.verbose` to `grunt.log`. 

However, after looking at the logging setup, it seems a bit odd to me that the elasticsearch logs get translated into grunt logs, level by level. For one, it means you have to change your log level in two different places if you want to enable debug logging for elasticsearch. Secondly, if you want to enable debug logging for elasticsearch, you have to enable it for **all** of the tasks in your grunt run, which is undesirable. In my opinion grunt logging and ES logging are two totally separate things and changing the log level for one shouldn't affect the other. I think grunt-esvm should pass through _all_ elasticsearch logs by default, and allow the user to control the ES log level via their ES config.

Thoughts? I'm no grunt expert, so there could be a better alternative I'm missing. My main desire is to be able to dial the ES log level up and down without blowing up my console with a bunch of debug logging from other unrelated grunt tasks.

**Comment by spalger** [comment]
That makes perfect sense, I like it.

**Comment by bevacqua** [comment]
Agreed.
